"use strict";
/* ===== Fichas de época (10-10-2026) =====
   Idea tomada de las «eras» de cerebrofilosofico.com, con contenido propio y comprobado. Una ficha por época de
   Ilustres (ant, med, ren, mod, ilu, con); se abren desde el título de la época en el listado de Ilustres, desde la
   etiqueta de época de cada ficha (#ilustres/epoca-<b>) y desde «La época» al final de los temas de HF.
   Campos: anos (rango), abre (lo que la inaugura), social, politico, ciencia, arte (11-10), pensamiento, rupturas (paso a la
   siguiente), trampa (caso trampa). Los pensadores se calculan de ILUSTRES (block). Vista: ilustresview.js.
   Campos opcionales (Fase 3, 10-10): nombre (título propio), block (bloque de ILUSTRES si la clave no lo es), nacidos [desde, hasta] (filtra por año de nacimiento), temasHF (temas de HF que enlazan aquí). Contemporánea se parte en con (siglo XIX) y con2 (siglos XX y XXI). Fuentes en #fuentes. Siete fichas: piloto (Ilustración) aprobado el 10-10; las demás escritas después, y Contemporánea partida en dos (Fase 3). */
const EPOCAS_FICHAS = {
 "ant": {
  "anos": "Del siglo VI a. C. al siglo V d. C. (por convención, hasta la caída de Roma en 476).",
  "abre": "<p>En las ciudades griegas de Jonia, como Mileto, unos pensadores empiezan a explicar la naturaleza sin recurrir a los dioses: es el paso <strong>del mito al logos</strong>. Según Heródoto, Tales predijo un eclipse de sol (el de 585 a. C.). Ayudan el comercio, el contacto con Egipto y Babilonia, la escritura alfabética y unas ciudades donde ninguna casta de sacerdotes controla el saber.</p>",
  "social": "<p>La vida gira en torno a la <strong>polis</strong>, la ciudad-estado. Solo los varones libres nacidos en ella son ciudadanos: las mujeres, los extranjeros residentes (metecos) y los esclavos quedan fuera. El tiempo libre para pensar (<em>scholé</em>, de donde viene «escuela») descansa en buena parte sobre el trabajo esclavo. Los niños se educan con los poemas de Homero, y en el siglo V a. C. los sofistas empiezan a cobrar por enseñar a hablar en público.</p>\n<p>Después de Alejandro, el centro del saber se traslada a <strong>Alejandría</strong>, con su Museo y su Biblioteca (siglo III a. C.), y más tarde a Roma, donde la filosofía griega se convierte en parte de la educación de las élites.</p>",
  "politico": "<p>Las polis son independientes y a menudo rivales. Atenas desarrolla la <strong>democracia</strong> tras las reformas de Clístenes (508 a. C.), vence a los persas en las guerras médicas (490-479 a. C.) y pierde la guerra del Peloponeso contra Esparta (431-404 a. C.); poco después condena a muerte a Sócrates (399 a. C.).</p>\n<p>Alejandro Magno crea un imperio enorme (336-323 a. C.) que se divide en reinos helenísticos, y estos acaban absorbidos por <strong>Roma</strong>, república y después imperio (desde el 27 a. C.). En el 380 el cristianismo pasa a ser la religión oficial del Imperio, y en el 476 cae el Imperio romano de Occidente.</p>",
  "ciencia": "<p>Los griegos convierten las técnicas de cálculo de Egipto y Babilonia en <strong>matemáticas demostrativas</strong>: los pitagóricos y, hacia el 300 a. C., los <em>Elementos</em> de Euclides. Eratóstenes calcula la circunferencia de la Tierra (siglo III a. C.); Aristarco propone que la Tierra gira alrededor del Sol, aunque se impondrá el modelo con la Tierra en el centro que Ptolomeo sistematiza en el siglo II. La medicina hipocrática busca causas naturales de las enfermedades, y Aristóteles funda la biología observando animales.</p>\n<p>La técnica, en cambio, avanza poco: con trabajo esclavo abundante, apenas hay interés por ahorrar esfuerzo con máquinas.</p>",
  "arte": "<p>El arte griego busca la <strong>proporción</strong>: el escultor Policleto fijó en su <em>Canon</em> las medidas ideales del cuerpo humano y las aplicó en el <em>Doríforo</em> (hacia 440 a. C.), y Fidias dirigió la decoración del <strong>Partenón</strong> (447-432 a. C.), que Pericles levantó en la Acrópolis tras las guerras médicas. De las figuras rígidas del periodo arcaico se pasa a cuerpos en movimiento y, en el helenismo, a la expresión del dolor, como en el <em>Laocoonte</em>.</p>\n<p>El <strong>teatro</strong> es una fiesta cívica: en las Dionisias de Atenas se representan las tragedias de Esquilo, Sófocles y Eurípides, y Aristófanes ridiculiza a Sócrates en <em>Las nubes</em> (423 a. C.). Los filósofos discuten el valor del arte: Platón desconfía de él porque imita las cosas, que ya son copias de las Ideas (<em>República</em> X), y Aristóteles defiende en la <em>Poética</em> que la tragedia purifica las emociones (<em>catarsis</em>). Roma aporta la ingeniería: el arco, la bóveda y el hormigón del <strong>Panteón</strong>; Vitruvio pide a la arquitectura solidez, utilidad y belleza.</p>",
  "pensamiento": "<ul>\n<li><strong>Presocráticos:</strong> buscan el <em>arché</em>, el principio de la naturaleza (<em>physis</em>): agua, aire, números, átomos.</li>\n<li><strong>Giro hacia el ser humano:</strong> los sofistas discuten si las leyes son naturales o convencionales, y Sócrates pregunta qué son la justicia y la virtud.</li>\n<li><strong>Grandes sistemas:</strong> Platón (las Ideas) y Aristóteles (la forma en las cosas) organizan todos los saberes.</li>\n<li><strong>Escuelas helenísticas:</strong> cínicos, epicúreos, estoicos y escépticos se preguntan, sobre todo, cómo vivir con serenidad en un mundo inseguro.</li>\n<li><strong>Final de la época:</strong> el neoplatonismo de Plotino y el encuentro con el cristianismo. Tertuliano preguntó qué tenía que ver Atenas con Jerusalén; otros, como Agustín, harán de la filosofía griega una aliada.</li>\n</ul>",
  "rupturas": "<p>La filosofía antigua no desaparece: el cristianismo la absorbe y la transforma. Agustín de Hipona lee la fe con ojos platónicos. En el 529 el emperador Justiniano prohíbe enseñar filosofía a los paganos en Atenas, y el saber griego sigue vivo sobre todo en Bizancio y, desde el siglo VIII, en el mundo islámico, donde Aristóteles se traduce al árabe y se comenta durante siglos.</p>",
  "trampa": "<p>«Los griegos inventaron la filosofía de la nada.» Bebieron de Egipto y de Babilonia, y no fueron los únicos: en los mismos siglos enseñaban Buda en la India y Confucio en China. Lo propio de los griegos fue convertir la discusión racional y pública en un método. Y otra trampa: la filosofía antigua no son solo Platón y Aristóteles, sino casi doce siglos de escuelas distintas.</p>"
 },
 "med": {
  "anos": "Del siglo V al siglo XV (en el eje del departamento, de 476 a 1492).",
  "abre": "<p>En el 476 cae el Imperio romano de Occidente. En medio de la ruina de las ciudades, la <strong>Iglesia</strong> se convierte en la institución que conserva la escritura, los libros y la enseñanza. Agustín de Hipona, que muere en el 430 mientras los vándalos asedian su ciudad, deja escrita la gran síntesis entre filosofía griega y fe cristiana que guiará los siglos siguientes.</p>",
  "social": "<p>Es una sociedad <strong>estamental</strong>: hacia el año 1000 se la describía como formada por los que rezan, los que combaten y los que trabajan. La mayoría vive en el campo, sometida a un señor (el <strong>feudalismo</strong>). Los monasterios copian y guardan los libros antiguos; los conventos son también uno de los pocos lugares donde las mujeres pueden estudiar y escribir, como Hildegarda de Bingen.</p>\n<p>Desde el siglo XI renacen las ciudades y el comercio, y nacen las <strong>universidades</strong> (Bolonia, París, Oxford, Salamanca). La peste negra (1347-1351) mata a una parte enorme de la población europea, quizá un tercio.</p>",
  "politico": "<p>Tras Roma surgen los reinos germánicos; Carlomagno es coronado emperador en el año 800. Al este sigue el <strong>Imperio bizantino</strong>, y desde el siglo VII el islam se extiende de Arabia a la península ibérica (al-Ándalus, desde el 711). Papas y emperadores se disputan durante siglos quién tiene la última palabra, y las cruzadas (1096-1291) enfrentan a cristianos y musulmanes.</p>\n<p>La época se cierra con dos fechas: la caída de Constantinopla en manos otomanas (1453) y, en 1492, la toma de Granada y la llegada de Colón a América.</p>",
  "ciencia": "<p>En la <strong>Bagdad</strong> de los siglos VIII-X se traducen al árabe Aristóteles, Euclides, Ptolomeo y Galeno. Al-Juarismi da nombre al <strong>álgebra</strong> y al algoritmo; Avicena escribe el <em>Canon de medicina</em>, estudiado en Europa durante siglos. En los siglos XII y XIII, en Toledo y en otros lugares, ese saber se traduce al latín, y Europa adopta los números indoarábigos y el cero.</p>\n<p>La técnica avanza más de lo que se suele creer: el arado pesado, los molinos, el reloj mecánico y, hacia 1450, la <strong>imprenta</strong> de tipos móviles de Gutenberg.</p>",
  "arte": "<p>El arte está al servicio de la fe y enseña a quien no sabe leer: hacia el año 600, el papa Gregorio Magno escribió que las pinturas de las iglesias son para los iletrados lo que la escritura para los que leen. En Bizancio estalla la <strong>querella iconoclasta</strong> (siglos VIII y IX): ¿se puede representar a Dios? Juan Damasceno defiende las imágenes porque Dios se hizo visible en Cristo. El arte islámico, en cambio, evita las figuras en los lugares sagrados y se llena de geometría y caligrafía, de la Mezquita de Córdoba a la <strong>Alhambra</strong> (siglo XIV).</p>\n<p>En Occidente, el <strong>románico</strong> (siglos XI-XII), de muros gruesos y pocas ventanas, crece a lo largo del Camino de Santiago. Desde 1140, con el abad Suger en Saint-Denis, el <strong>gótico</strong> abre los muros a la luz de las vidrieras, que se entendía como imagen de Dios. El historiador Erwin Panofsky (1951) comparó la catedral gótica con la <em>Suma</em> escolástica, ordenada en partes y artículos; la comparación es sugerente, pero discutida. Dante cierra la época con la <em>Divina comedia</em>, donde Tomás de Aquino aparece en el Paraíso.</p>",
  "pensamiento": "<ul>\n<li><strong>Fe y razón:</strong> el gran problema de la época es cómo encajar lo que se cree con lo que se demuestra.</li>\n<li><strong>Patrística:</strong> los Padres de la Iglesia, con Agustín a la cabeza, piensan la fe con herramientas platónicas.</li>\n<li><strong>Escolástica:</strong> en las escuelas y universidades se razona con un método riguroso (lectura, cuestión, disputa). Anselmo propone su argumento ontológico; Tomás de Aquino armoniza a Aristóteles con la fe.</li>\n<li><strong>Filosofía en árabe y en hebreo:</strong> Avicena, Averroes y Maimónides piensan los mismos problemas desde el islam y el judaísmo.</li>\n<li><strong>Los universales:</strong> ¿existe «el ser humano» además de cada ser humano? Abelardo y Ockham responden que son nombres o conceptos.</li>\n</ul>",
  "rupturas": "<p>En el siglo XIV, Ockham separa la fe de la razón: lo que se cree no puede demostrarse, y la navaja que lleva su nombre recorta las entidades innecesarias. La peste, el Cisma de Occidente (1378-1417), con dos y hasta tres papas a la vez, y la crítica de los humanistas italianos a la escolástica abren paso al Renacimiento. La imprenta hará el resto.</p>",
  "trampa": "<p>«La Edad Media fue una época oscura.» El nombre lo inventaron los humanistas para despreciarla, pero en ella nacieron las universidades, la lógica alcanzó un nivel muy alto y se tradujo medio saber antiguo. Y no: los sabios medievales no creían que la Tierra fuera plana; su forma esférica se enseñaba en las universidades, por ejemplo con el <em>Tratado de la esfera</em> de Sacrobosco (siglo XIII).</p>"
 },
 "ren": {
  "anos": "De mediados del siglo XV a finales del siglo XVI (en el eje del departamento, de 1492 a 1600).",
  "abre": "<p>Tres novedades cambian el mundo en pocos años: la <strong>imprenta</strong> (hacia 1450), que multiplica los libros; la llegada a Italia de sabios y manuscritos griegos de Bizancio; y la llegada de Colón a América (1492), que demuestra que el mundo conocido por los antiguos era solo una parte.</p>",
  "social": "<p>Las ciudades italianas, como Florencia o Venecia, se enriquecen con el comercio y la banca, y familias como los Médici pagan a artistas y sabios (el <strong>mecenazgo</strong>). Los libros impresos llegan a más gente, y aparece la figura del humanista que vive de escribir, enseñar o aconsejar a los príncipes.</p>\n<p>La conquista de América destruye sociedades enteras y abre el comercio atlántico de personas esclavizadas. También provoca un debate filosófico: en la Junta de Valladolid (1550-1551), Bartolomé de las Casas y Juan Ginés de Sepúlveda discuten si los pueblos indígenas pueden ser sometidos.</p>",
  "politico": "<p>Se forman los <strong>Estados modernos</strong>, con reyes que concentran el poder (los Reyes Católicos, Francia, Inglaterra). Italia, dividida en pequeños estados, es campo de batalla de las grandes potencias: en ese contexto escribe Maquiavelo <em>El príncipe</em> (1513).</p>\n<p>En 1517 Lutero publica sus 95 tesis y comienza la <strong>Reforma</strong> protestante. Europa se divide religiosamente: guerras de religión, la Paz de Augsburgo (1555), que deja a cada príncipe elegir la religión de sus súbditos, y la respuesta católica del Concilio de Trento (1545-1563).</p>",
  "ciencia": "<p>En 1543 aparecen dos libros decisivos: <em>Sobre las revoluciones de las esferas celestes</em> de Copérnico, que pone el Sol en el centro, y la anatomía de Vesalio, que corrige a Galeno a partir de disecciones. Leonardo da Vinci une arte, observación e ingeniería. La <strong>revolución científica</strong> empieza aquí y culminará en el siglo XVII con Kepler, Galileo, Harvey y Newton.</p>",
  "arte": "<p>Hacia 1420, Brunelleschi demuestra en Florencia la <strong>perspectiva lineal</strong>, y Alberti la explica en <em>Sobre la pintura</em> (1435): el cuadro es una ventana abierta al mundo, construida con geometría. El artista deja de ser un artesano y quiere ser un intelectual: Leonardo da Vinci defiende que la pintura es una ciencia. Miguel Ángel, Rafael y Durero firman sus obras y se hacen famosos.</p>\n<p>Los temas antiguos vuelven junto a los cristianos. En <strong><em>La escuela de Atenas</em></strong> (1509-1511), en el Vaticano, Rafael pinta a Platón señalando al cielo con el <em>Timeo</em> y a Aristóteles con la mano hacia la tierra y la <em>Ética</em>. <em>El nacimiento de Venus</em> de Botticelli (hacia 1485) se ha leído desde el neoplatonismo de Ficino, aunque los historiadores no se ponen de acuerdo. La Reforma divide Europa también en el arte: los protestantes retiran imágenes de las iglesias y el Concilio de Trento (1563) las defiende, pero vigila que no enseñen errores.</p>",
  "pensamiento": "<ul>\n<li><strong>Humanismo:</strong> vuelta a los textos clásicos en su lengua original y confianza en la dignidad del ser humano, capaz de hacerse a sí mismo (Pico della Mirandola, <em>Discurso sobre la dignidad del hombre</em>, 1486).</li>\n<li><strong>Crítica y tolerancia:</strong> Erasmo se burla de los abusos de su tiempo en el <em>Elogio de la locura</em> (1511) y defiende una religión interior y pacífica.</li>\n<li><strong>Utopías:</strong> Tomás Moro (<em>Utopía</em>, 1516) y, más tarde, Campanella imaginan sociedades justas para criticar las reales.</li>\n<li><strong>Realismo político:</strong> Maquiavelo separa la política de la moral religiosa.</li>\n<li><strong>Una naturaleza infinita:</strong> Nicolás de Cusa y Giordano Bruno, quemado por la Inquisición en 1600, piensan un universo sin límites.</li>\n</ul>",
  "rupturas": "<p>Al final del siglo XVI la autoridad de la Iglesia está dividida y la de Aristóteles, en entredicho. Montaigne duda de casi todo. La pregunta que hereda la Modernidad es dónde encontrar un fundamento seguro para el conocimiento: Francis Bacon propone un método basado en la experiencia (<em>Novum organum</em>, 1620) y Descartes, en la razón (<em>Discurso del método</em>, 1637).</p>\n<p>En Ilustres, Descartes aparece en esta época porque el eje del departamento la cierra en 1600 y él nació en 1596; pero su obra abre la filosofía moderna.</p>",
  "trampa": "<p>«En el Renacimiento la ciencia derrotó a la religión.» Copérnico era canónigo de la Iglesia, y Kepler y Galileo eran creyentes. Además, junto a la nueva ciencia florecieron la magia, la astrología y la alquimia, que muchos humanistas tomaban muy en serio.</p>"
 },
 "mod": {
  "anos": "El siglo XVII (en el eje del departamento, la filosofía moderna va de 1600 a 1800; la Ilustración tiene aquí su propia ficha).",
  "abre": "<p>La <strong>revolución científica</strong> cambia la manera de conocer. Galileo apunta su telescopio al cielo (1610) y defiende que el libro de la naturaleza está escrito en lengua matemática (<em>El ensayador</em>, 1623). Con la autoridad de los antiguos en crisis, Descartes busca empezar de cero, desde una verdad que no se pueda dudar (<em>Discurso del método</em>, 1637).</p>",
  "social": "<p>Es un siglo de crisis: la <strong>guerra de los Treinta Años</strong> (1618-1648) arrasa Europa central, y las epidemias y las malas cosechas son frecuentes. Los Países Bajos, república comercial y relativamente tolerante, acogen a pensadores perseguidos o incómodos: allí vivieron Descartes y Spinoza, a quien su comunidad judía expulsó en 1656.</p>\n<p>Los sabios forman una «república de las letras» que se escribe cartas por toda Europa, como las de Descartes e Isabel de Bohemia, y nacen las primeras <strong>academias científicas</strong>: la Royal Society de Londres (1660) y la Academia de Ciencias de París (1666).</p>",
  "politico": "<p>Triunfa el <strong>absolutismo</strong>: el rey concentra todo el poder, como Luis XIV en Francia (reinó de 1643 a 1715). La Paz de Westfalia (1648) organiza Europa en Estados soberanos. Inglaterra es la excepción: una guerra civil (1642-1651) termina con la ejecución del rey Carlos I en 1649, y la Revolución Gloriosa (1688-1689) limita el poder de la corona. Hobbes escribe el <em>Leviatán</em> (1651) tras la guerra; Locke, sus <em>Dos tratados sobre el gobierno civil</em> (1689) tras la revolución.</p>",
  "ciencia": "<p>Kepler descubre que los planetas giran en elipses; Harvey demuestra la circulación de la sangre (1628); el microscopio revela un mundo invisible (Hooke, <em>Micrographia</em>, 1665). Newton y Leibniz inventan por separado el <strong>cálculo infinitesimal</strong>, y Newton une la física del cielo y la de la Tierra en una sola ley de la gravedad (1687).</p>\n<p>La imagen dominante es el <strong>mecanicismo</strong>: el mundo funciona como un gran reloj, con piezas que se mueven por contacto según leyes matemáticas.</p>",
  "arte": "<p>El <strong>Barroco</strong> quiere conmover y convencer. La Iglesia de la Contrarreforma usa el teatro de las emociones: el <em>Éxtasis de santa Teresa</em> de Bernini (1647-1652) o el claroscuro de Caravaggio. Las monarquías absolutas convierten el arte en propaganda del poder, como el palacio de Versalles de Luis XIV. En la Holanda burguesa y protestante, en cambio, se pintan interiores, paisajes y retratos de comerciantes (Rembrandt, Vermeer). Nace la ópera: <em>L’Orfeo</em> de Monteverdi es de 1607.</p>\n<p>Arte y filosofía comparten preguntas. <em>La vida es sueño</em> de Calderón (1635) duda, como Descartes, de que podamos distinguir el sueño de la vigilia. <em>Don Quijote</em> (1605-1615) juega con la locura, la ficción y la realidad. En <em>Las meninas</em> (1656), Velázquez se pinta a sí mismo pintando y pone a los reyes en un espejo, fuera del cuadro; Michel Foucault abrió con este cuadro <em>Las palabras y las cosas</em> (1966) para hablar de cómo se representa el mundo.</p>",
  "pensamiento": "<ul>\n<li><strong>El método y la certeza:</strong> antes de saber qué hay, hay que saber cómo podemos conocerlo.</li>\n<li><strong>Racionalismo:</strong> Descartes, Spinoza, Malebranche y Leibniz confían en ideas que la razón conoce por sí misma.</li>\n<li><strong>Empirismo:</strong> Locke y Berkeley sostienen que todo conocimiento procede de la experiencia; Hume lo llevará al límite en el siglo siguiente.</li>\n<li><strong>Sustancia:</strong> ¿cuántas hay? Dos para Descartes (mente y materia), una para Spinoza, infinitas mónadas para Leibniz, solo materia para Hobbes.</li>\n<li><strong>Contrato social y tolerancia:</strong> Hobbes y Locke fundan el poder en un pacto; Spinoza (1670) y Locke (1689) defienden la libertad de pensamiento y la tolerancia religiosa.</li>\n</ul>",
  "rupturas": "<p>Newton y Locke se convierten en los modelos de la generación siguiente: Voltaire los da a conocer en Francia en sus <em>Cartas filosóficas</em> (1734). La confianza en la razón, que el siglo XVII aplicó sobre todo a la naturaleza, la Ilustración la extenderá a la sociedad, la política y la religión.</p>",
  "trampa": "<p>«Racionalistas y empiristas eran dos equipos enfrentados.» La etiqueta la pusieron después los historiadores. Todos se leían y se respondían: Locke discute con Descartes, y Leibniz dedicó un libro entero a contestar a Locke (<em>Nuevos ensayos sobre el entendimiento humano</em>). Y casi todos compartían la confianza en las matemáticas y en la nueva física.</p>"
 },
 "ilu": {
  "anos": "De finales del siglo XVII (hacia 1680) a 1800, aproximadamente.",
  "abre": "<p>La revolución científica culmina con los <em>Principios matemáticos de la filosofía natural</em> de Newton (1687): el universo obedece a leyes que la razón puede descubrir. Al año siguiente, la Revolución Gloriosa inglesa (1688-1689) somete al rey a una declaración de derechos del Parlamento. Razón y libertad política son las dos ideas que la época llevará más lejos.</p>",
  "social": "<p>Crece una <strong>burguesía</strong> de comerciantes, médicos, abogados y funcionarios que lee, discute y quiere influir. Nacen lugares de conversación fuera de la corte y de la Iglesia: los <strong>cafés</strong>, las academias, las logias y los <strong>salones</strong>, muchos dirigidos por mujeres, como el de Madame Geoffrin en París. Se multiplican los periódicos y los libros baratos, y aparece algo nuevo: la <strong>opinión pública</strong>.</p>\n<p>Pero la Ilustración fue cosa de minorías: la mayoría de la población era campesina y no sabía leer. Y la riqueza de los puertos europeos dependía en buena parte del comercio atlántico de personas esclavizadas.</p>",
  "politico": "<p>Casi toda Europa vive en <strong>monarquías absolutas</strong>. Algunos reyes adoptan reformas ilustradas sin ceder poder (el llamado <strong>despotismo ilustrado</strong>: Federico II de Prusia, Catalina II de Rusia, Carlos III en España). La censura sigue activa: la <em>Enciclopedia</em> fue prohibida en Francia en 1759 y siguió publicándose a escondidas.</p>\n<p>Al final del siglo, dos revoluciones llevan las ideas a la política: la <strong>independencia de los Estados Unidos</strong> (1776), con su declaración de derechos, y la <strong>Revolución francesa</strong> (1789), con la <em>Declaración de los derechos del hombre y del ciudadano</em>.</p>",
  "ciencia": "<p>Newton se convierte en el modelo de todo saber: observar, medir y buscar leyes. Linneo clasifica los seres vivos (<em>Sistema de la naturaleza</em>, 1735); Lavoisier funda la química moderna (<em>Tratado elemental de química</em>, 1789); Jenner prueba la primera vacuna, contra la viruela (1796). En Gran Bretaña, la máquina de vapor de Watt (patentada en 1769) abre la <strong>Revolución industrial</strong>.</p>\n<p>La <em>Enciclopedia</em> de Diderot y d'Alembert (1751-1772) quiere reunir todo el saber, también el de los oficios, con láminas de talleres y máquinas: el conocimiento técnico pasa a ser digno de la filosofía.</p>",
  "arte": "<p>Frente al <strong>rococó</strong>, decorativo y galante (Watteau, Fragonard), triunfa a finales de siglo el <strong>neoclasicismo</strong>: Winckelmann propone imitar a los griegos, con su «noble sencillez y serena grandeza» (1755), y David pinta virtudes cívicas romanas en <em>El juramento de los Horacios</em> (1784), poco antes de la Revolución. Diderot inventa la crítica de arte con sus comentarios de las exposiciones de París (<em>Salones</em>), y la música alcanza su forma clásica con Haydn y Mozart.</p>\n<p>Nace la <strong>estética</strong> como parte de la filosofía. Baumgarten pone el nombre (<em>Aesthetica</em>, 1750); Hume se pregunta si hay una norma del gusto (1757); Burke separa lo bello de lo sublime, lo inmenso que nos asusta y nos atrae (1757); y Kant, en la <em>Crítica del juicio</em> (1790), define lo bello como lo que agrada sin interés y sin concepto. Goya pone la nota crítica: en sus <em>Caprichos</em> (1799), «El sueño de la razón produce monstruos» puede leerse como elogio de la razón despierta o como aviso de sus límites.</p>",
  "pensamiento": "<p>La idea central la resumió Kant en 1784: la Ilustración es la salida del ser humano de una minoría de edad de la que él mismo es culpable; su lema, <em>sapere aude</em>, «¡ten el valor de servirte de tu propio entendimiento!» (<em>¿Qué es la Ilustración?</em>). De ahí sus grandes rasgos:</p>\n<ul>\n<li><strong>Razón crítica:</strong> nada se acepta por tradición o autoridad sin examinarlo, ni siquiera la propia razón (Hume, Kant).</li>\n<li><strong>Progreso:</strong> el saber y la educación pueden mejorar la vida humana (Rousseau, <em>Emilio</em>, 1762).</li>\n<li><strong>Tolerancia</strong> religiosa y crítica de la superstición (Voltaire, <em>Tratado sobre la tolerancia</em>, 1763). Muchos ilustrados son deístas: creen en un Dios creador, pero no en las religiones reveladas.</li>\n<li><strong>Derechos y división de poderes</strong> frente al absolutismo (Montesquieu, <em>El espíritu de las leyes</em>, 1748; Rousseau, <em>El contrato social</em>, 1762).</li>\n<li><strong>Felicidad y utilidad:</strong> la moral se piensa desde el sentimiento (Hume) o desde las consecuencias (Bentham), y la economía como un saber propio (Adam Smith, <em>La riqueza de las naciones</em>, 1776).</li>\n<li>Primeras voces por la <strong>igualdad de las mujeres</strong>: Olympe de Gouges (1791) y Mary Wollstonecraft (1792).</li>\n</ul>",
  "rupturas": "<p>La Ilustración no termina de golpe. En Alemania, Hamann y Herder le reprochan olvidar el sentimiento, la lengua y la historia de cada pueblo, y el <strong>Romanticismo</strong> recoge esa crítica. El Terror de la Revolución francesa (1793-1794) hace preguntarse si la razón puede rehacer una sociedad entera. Kant cierra la época y la examina a la vez: sus <em>Críticas</em> marcan los límites de la razón.</p>\n<p>Otras líneas siguen en el siglo XIX: el <strong>utilitarismo</strong> y el <strong>liberalismo</strong> de Bentham y Mill (por eso en Ilustres van en esta época), y la fe en el progreso, que heredan Hegel y Marx. En el siglo XX, Adorno y Horkheimer (<em>Dialéctica de la Ilustración</em>, 1944) se preguntan por qué la razón ilustrada no impidió la barbarie.</p>",
  "trampa": "<p>«La Ilustración fue francesa.» París fue su capital más visible, pero hubo una Ilustración escocesa (Hume, Smith), una alemana (Kant, Lessing, Mendelssohn), una española (Feijoo, Jovellanos) y una americana (Franklin, Jefferson). Y «ilustrado» no quiere decir «ateo»: Holbach lo era, pero Voltaire era deísta y Kant defendía una fe racional.</p>"
 },
 "con": {
  "nombre": "Contemporánea I: el siglo XIX",
  "block": "con",
  "nacidos": [
   1700,
   1849
  ],
  "temasHF": [
   21
  ],
  "anos": "Del final del siglo XVIII a la Primera Guerra Mundial (de 1800 a 1914, aproximadamente).",
  "abre": "<p>La Revolución francesa y las guerras de Napoleón cambian el mapa político de Europa, y la <strong>Revolución industrial</strong> cambia la manera de vivir y de trabajar. En filosofía, Kant ha dejado abierta la pregunta por los límites de la razón, y el idealismo alemán intenta superarlos: Hegel publica la <em>Fenomenología del espíritu</em> en 1807.</p>",
  "social": "<p>Las fábricas atraen a millones de personas del campo a las ciudades. Nace el <strong>proletariado</strong>, con jornadas larguísimas y trabajo infantil, como describen las novelas de Dickens, y con él el movimiento obrero, los sindicatos y los socialismos: los llamados utópicos (Owen, Fourier, Saint-Simon) y el de Marx y Engels (<em>Manifiesto comunista</em>, 1848). La burguesía se convierte en la clase dirigente, y la escuela y la prensa llegan a capas cada vez más amplias de la población.</p>",
  "politico": "<p>Es el siglo de las revoluciones liberales (1830, 1848), de las constituciones y de los <strong>nacionalismos</strong>: Italia se unifica en 1861 y Alemania en 1871. Las potencias europeas se reparten África y buena parte de Asia en <strong>imperios coloniales</strong> (Conferencia de Berlín, 1884-1885). La esclavitud se va aboliendo: en el Imperio británico en 1833, en los Estados Unidos en 1865 tras una guerra civil, en la Cuba española en 1886.</p>",
  "ciencia": "<p>Darwin explica la evolución de las especies por selección natural (<em>El origen de las especies</em>, 1859) y Mendel descubre las leyes de la herencia (1866). Faraday y Maxwell unifican la electricidad y el magnetismo; Pasteur demuestra el papel de los microbios en las enfermedades. El ferrocarril, el telégrafo y la electricidad transforman la vida diaria. Boole y Frege empiezan a convertir la lógica en una rama de las matemáticas.</p>",
  "arte": "<p>El <strong>Romanticismo</strong> exalta el sentimiento, la naturaleza salvaje y el genio que crea sus propias reglas: <em>El caminante sobre el mar de nubes</em> de Caspar David Friedrich (hacia 1818) o las sinfonías de Beethoven. La filosofía le da un lugar muy alto al arte: para Hegel es la manifestación sensible de la verdad, aunque cree que en su época ya ha sido superado por la filosofía; para Schopenhauer, la música expresa directamente la voluntad; Nietzsche, en <em>El nacimiento de la tragedia</em> (1872), opone lo apolíneo (orden, forma) a lo dionisíaco (embriaguez, vida) y ve en Wagner un renacer de la tragedia.</p>\n<p>A mitad de siglo, el <strong>realismo</strong> pinta a los trabajadores y la vida corriente: Courbet, <em>Los picapedreros</em> (1849). La fotografía (1839) libera a la pintura de copiar la realidad, y los <strong>impresionistas</strong> pintan la luz y el instante: el cuadro de Monet <em>Impresión, sol naciente</em> dio nombre al grupo en 1874. La arquitectura de hierro y cristal de la industria (la Torre Eiffel, 1889) anuncia un arte nuevo.</p>",
  "pensamiento": "<ul>\n<li><strong>Idealismo y Romanticismo:</strong> Fichte, Schelling y Hegel piensan la realidad como despliegue del espíritu; Novalis, Schlegel y Hölderlin reivindican el sentimiento, el arte y la historia de cada pueblo.</li>\n<li><strong>Positivismo:</strong> Comte sostiene que el saber culmina en la ciencia positiva, basada en hechos observables.</li>\n<li><strong>Utilitarismo y liberalismo:</strong> Mill defiende la libertad individual frente al Estado y frente a la presión de la mayoría (<em>Sobre la libertad</em>, 1859).</li>\n<li><strong>Socialismo y anarquismo:</strong> Marx, Proudhon y Kropotkin critican la propiedad y el capitalismo desde posiciones distintas.</li>\n<li><strong>Sospecha:</strong> Marx y Nietzsche buscan detrás de las ideas los intereses económicos o la voluntad de poder.</li>\n</ul>",
  "rupturas": "<p>El siglo XIX confía en el <strong>progreso</strong>: las exposiciones universales muestran máquinas cada vez más asombrosas. Pero dentro de él crecen las grietas: Nietzsche anuncia la «muerte de Dios» (1882), Freud explora un inconsciente que la razón no controla (<em>La interpretación de los sueños</em>, 1900) y la física clásica empieza a tambalearse (Einstein, 1905). La Primera Guerra Mundial (1914) rompe definitivamente aquella confianza.</p>",
  "trampa": "<p>«Contemporáneo quiere decir de hoy.» En historia, la Edad Contemporánea empieza a finales del siglo XVIII: Hegel y Marx son filósofos «contemporáneos» aunque vivieran hace dos siglos. Por eso en esta web la época se divide en dos fichas: el siglo XIX y los siglos XX y XXI.</p>"
 },
 "con2": {
  "nombre": "Contemporánea II: siglos XX y XXI",
  "block": "con",
  "nacidos": [
   1850,
   2100
  ],
  "temasHF": [
   22,
   23,
   24,
   25,
   26,
   27
  ],
  "anos": "De la Primera Guerra Mundial (1914) a hoy.",
  "abre": "<p>La <strong>Primera Guerra Mundial</strong> (1914-1918), con millones de muertos en las trincheras y armas fabricadas en serie, rompe la confianza del siglo XIX en el progreso. En 1917, la Revolución rusa promete una sociedad sin clases. El siglo empieza preguntándose qué ha fallado en la civilización que se creía más avanzada.</p>",
  "social": "<p>Llega la <strong>sociedad de masas</strong>: grandes ciudades, consumo, cine, radio y televisión. Las mujeres conquistan el voto (en España, en 1931) y la escuela llega a casi todos. En la segunda mitad del siglo se extiende en Europa el <strong>Estado de bienestar</strong>, con sanidad y pensiones públicas.</p>\n<p>Hoy vivimos en un mundo <strong>globalizado</strong> y conectado por internet, con desigualdades enormes, grandes migraciones y una crisis ecológica que obliga a repensar el progreso.</p>",
  "politico": "<p>Entre las dos guerras mundiales surgen los <strong>totalitarismos</strong> (fascismo, nazismo, estalinismo). La Segunda Guerra Mundial (1939-1945) termina con el Holocausto y con las bombas atómicas de Hiroshima y Nagasaki. Después nacen la ONU y la Declaración Universal de los Derechos Humanos (1948), comienza la Guerra Fría y se descolonizan Asia y África.</p>\n<p>En España, la dictadura franquista (1939-1975) lleva al exilio a muchos pensadores, como María Zambrano. La caída del muro de Berlín (1989) cierra la Guerra Fría; el siglo XXI trae la crisis financiera de 2008, la pandemia de covid-19 (2020) y nuevas guerras.</p>",
  "ciencia": "<p>Einstein (relatividad) y la mecánica cuántica cambian la idea de espacio, tiempo y materia. En 1953 se describe la estructura del ADN, con datos de Rosalind Franklin. Turing (1936) y Shannon (1948) ponen las bases de la informática. La energía nuclear, el viaje a la Luna (1969), internet y la inteligencia artificial muestran un poder técnico enorme, que obliga a preguntarse por sus límites.</p>",
  "arte": "<p>Las <strong>vanguardias</strong> rompen con la tradición: el cubismo de Picasso y Braque descompone las formas desde 1907; el dadaísmo nace en Zúrich en 1916 como burla de una civilización que ha producido la guerra; y Marcel Duchamp presenta un urinario con el título <em>Fuente</em> (1917). Desde entonces, la pregunta «¿qué es arte?» forma parte del arte. El surrealismo (manifiesto de Breton, 1924) busca el inconsciente que había descrito Freud. El <em>Guernica</em> de Picasso (1937) denuncia el bombardeo de la ciudad, y ese mismo año los nazis exponen el arte moderno como «arte degenerado».</p>\n<p>La técnica cambia el arte. Walter Benjamin escribió en 1936 que la reproducción en serie, como la fotografía y el cine, hace que la obra pierda su «aura» de pieza única; Adorno y Horkheimer criticaron la <strong>industria cultural</strong>, que fabrica entretenimiento como mercancía. Cuando Andy Warhol expuso sus cajas de estropajos <em>Brillo</em> (1964), el filósofo Arthur Danto concluyó que lo que hace arte a un objeto no es su aspecto, sino una teoría y un «mundo del arte» que lo reconoce. Hoy el debate sigue con el arte digital y las imágenes hechas con inteligencia artificial: ¿quién es el autor?</p>",
  "pensamiento": "<ul>\n<li><strong>Psicoanálisis:</strong> Freud muestra que no somos dueños del todo de nuestra mente.</li>\n<li><strong>Existencia y fenomenología:</strong> Heidegger, Sartre, Beauvoir y Camus parten de la existencia concreta, la libertad y la angustia.</li>\n<li><strong>Giro lingüístico:</strong> Wittgenstein y la filosofía analítica examinan el lenguaje; Popper y Kuhn, la ciencia.</li>\n<li><strong>Teoría crítica:</strong> la Escuela de Fráncfort (Horkheimer, Adorno, Habermas) analiza la sociedad de masas.</li>\n<li><strong>Filosofía en España:</strong> Unamuno, Ortega y Zambrano; en euskera, Txillardegi y Azurmendi.</li>\n<li><strong>Debates de hoy:</strong> feminismo (Beauvoir, Butler), posmodernidad (Lyotard, Foucault, Derrida), justicia (Rawls), ecología (Yayo Herrero), tecnología y mente (Han, Bostrom, Chalmers).</li>\n</ul>",
  "rupturas": "<p>Es una época que no ha terminado, con varios cortes internos. Auschwitz e Hiroshima obligan a preguntar qué ha hecho la razón (Adorno, Arendt); en 1979, Lyotard anuncia el fin de los «grandes relatos». Las preguntas abiertas hoy, como la inteligencia artificial, la crisis climática o la desinformación, quizá estén abriendo ya otra época que todavía no sabemos nombrar.</p>",
  "trampa": "<p>«En la filosofía actual todo vale.» Que haya muchas corrientes no significa que cualquier opinión sirva: cada una discute con razones con las demás. Y «posmoderno» no es un insulto ni quiere decir «muy moderno»: es una tesis concreta sobre el fin de los grandes relatos, que también tiene críticos, como Habermas.</p>"
 }
};
