// Generado por tools/build_subject.js (fil) — alumnado, sin material del profesor.
const MAPS = {
 "map-fil-que-es": {
  "subject": "fil",
  "tema": "Filosofía · Tema 1",
  "title": "¿Qué es la filosofía?",
  "md": "# ¿Qué es la filosofía?\n## Qué es\n### Amor a la sabiduría\n- *Philía* (amor) + *sophía* (sabiduría)\n- El filósofo **busca** la verdad, no la posee\n- Nace del **asombro**, la curiosidad y la duda\n- «Solo sé que no sé nada» (**Sócrates**)\n### Del mito al logos\n- Grecia, **s. VI a. C.**\n- **Mito**: relato de dioses; antropomórfico, arbitrario, **dogmático**\n- **Logos**: causas naturales y **argumentos**; **crítico**\n- **Tales de Mileto** busca el **arché**\n## Qué tipo de saber es\n### Los tipos de saber\n- **Común**: espontáneo, no reflexivo\n- **Científico**: causas próximas; **parcial**\n- **Filosófico**: causas últimas; la realidad **en su conjunto**\n### Rasgos del saber filosófico\n- **Racional** y **crítico**\n- **Radical**: va a la raíz\n- **Universal** y **sistemático**\n- **Práctico**: ética y política\n- **Abierto** e **histórico**\n### Con los otros saberes\n- **Ciencia**: datos y experimentos\n- **Religión**: fe y revelación\n- **Arte**: obras que hacen sentir\n- **Filosofía**: conceptos y argumentos\n## Qué estudia y para qué\n### Las ramas\n- **Metafísica**: qué es ser, qué existe\n- **Teoría del conocimiento**: qué podemos conocer\n- **Ética** y **filosofía política**\n- **Estética**, **lógica** y **antropología**\n### Para qué sirve\n- Pensar por uno mismo\n- Leer y comentar **textos**"
 },
 "map-filosofia-ciencia": {
  "subject": "fil",
  "tema": "Filosofía · Filosofía de la ciencia",
  "title": "Filosofía de la ciencia",
  "md": "# Filosofía de la ciencia\n## Preguntas centrales\n- ¿Qué es el **conocimiento científico**?\n- ¿Cómo se obtiene?\n- ¿Qué distingue la ciencia de otros saberes?\n## Filosofía de la física\n- **Espacio y tiempo** — Newton vs Leibniz; relatividad; cuántica\n- **Causalidad** — determinismo vs indeterminismo\n## Epistemología científica\n- **Realismo** — las teorías describen la verdad\n- **Instrumentalismo** — las teorías son herramientas\n- **Construcción social** del conocimiento\n- Prueba: **inducción**, **falsación** (Popper), teorema de Bayes\n## Metodología\n- **Método científico** — observación, hipótesis, experimentación, teoría\n- Clasificación: ciencias formales, físicas, biológicas y sociales\n## Filosofía de las matemáticas\n- **Platonismo** — los objetos matemáticos existen\n- **Nominalismo** — solo son lenguaje\n- **Intuicionismo** — son una construcción humana\n## Historia de la ciencia\n- Revoluciones: **Copérnico**, **Newton**, **Einstein**, cuántica\n- **Galileo** — inicio de la revolución científica"
 },
 "map-ser-humano": {
  "subject": "fil",
  "tema": "Filosofía · Tema 2",
  "title": "¿Qué es el ser humano?",
  "md": "# ¿Qué es el ser humano?\n## Naturaleza, cultura e historia\n### Naturaleza y cultura\n- **Evolución** → **hominización** (biológica)\n- **Cultura** → **humanización** (aprendida)\n- Dialéctica naturaleza-cultura; nacemos «inacabados»\n### Cultura, identidad y diversidad\n- **Socialización**; identidad personal y colectiva\n- **Etnocentrismo / relativismo / interculturalidad**\n### Concepciones en la historia\n- Antigüedad — animal **racional** y social\n- Edad Media — criatura a imagen de Dios\n- Modernidad — sujeto que piensa (Descartes); **dignidad** (Kant)\n- Contemporánea — Marx (trabajo), Nietzsche, existencialismo (**proyecto** y libertad)\n## Cuerpo, mente y conciencia\n### Cuerpo y mente\n- **Dualismo** — Platón (cárcel del alma); Descartes (res cogitans / res extensa)\n- **Monismo / materialismo** — somos cuerpo\n- Aristóteles — el alma, **forma** del cuerpo\n### Conciencia, lenguaje y persona\n- **Conciencia** y autoconciencia (introspección)\n- **Lenguaje** simbólico\n- **Persona** — dignidad; fin en sí misma\n## Identidad y sentido\n### Identidad personal\n- Barco de Teseo; **memoria** (Locke); Hume; el relato\n- **Transhumanismo**\n### El sentido de la existencia\n- Absurdo / trascendente / inmanente / **darse sentido uno mismo**"
 },
 "map-conocimiento": {
  "subject": "fil",
  "tema": "Filosofía · Tema 3",
  "title": "¿Qué podemos conocer?",
  "md": "# ¿Qué podemos conocer?\n## El conocimiento humano\n- Relación **sujeto — objeto**\n- Grados: **sensación → percepción → concepto** (abstracción)\n- La rama: **epistemología / gnoseología**\n## Las fuentes del conocimiento\n- **Racionalismo** (Descartes) — la razón; ideas innatas\n- **Empirismo** (Locke, Hume) — la experiencia; *tabula rasa*\n- **Criticismo** (Kant) — experiencia + razón\n## ¿Podemos alcanzar la verdad?\n- **Dogmatismo** · **Escepticismo** · **Relativismo** · **Criticismo**\n## La cuestión de la verdad\n- Opinión (**doxa**) frente a ciencia (**episteme**)\n- Teorías: **correspondencia**, coherencia, consenso, pragmática\n## La posverdad\n- Los hechos pesan menos que las emociones\n- Bulos, **fake news**, sesgos, cámaras de eco\n- Defensa: **pensamiento crítico** y contrastar fuentes\n## El saber científico\n- Ciencias **formales** y **empíricas** (naturales / sociales)\n- **Método hipotético-deductivo**; Popper (falsabilidad), Kuhn (paradigmas)\n## Ciencia, tecnología y arte\n- Ciencia / técnica / **tecnología**; límites éticos\n- La **mujer en la ciencia**"
 },
 "map-racionalismo-empirismo": {
  "subject": "fil",
  "tema": "Filosofía · Racionalismo y empirismo",
  "title": "Racionalismo vs. empirismo",
  "md": "# Racionalismo vs. empirismo\n## El problema\n- Edad Moderna: ¿cuál es el **fundamento del conocimiento**?\n## Racionalismo\n- Representante: **Descartes**\n- Fuente: la **razón** — conocimiento **a priori**\n- **Ideas innatas**: Dios (res infinita), res cogitans, res extensa\n- **Dogmatismo**: no duda de la capacidad de la razón\n- Verdades **universales y necesarias**\n- Método **deductivo**; modelo: las **matemáticas**\n## Empirismo\n- Representantes: **Locke** y **Hume**\n- Fuente: la **experiencia** — conocimiento **a posteriori**\n- Locke — la mente al nacer es **tabula rasa**\n- Hume — duda de la **causalidad** (hábito) → **escepticismo**\n- Verdades generales y **provisionales**\n- Método **inductivo**; modelo: la **ciencia experimental**\n## Síntesis: Kant\n- El **criticismo** une razón y experiencia\n- Redefine filosofía, metafísica y ciencia"
 },
 "map-fil-mito-logos": {
  "subject": "fil",
  "tema": "Filosofía · Tema 1",
  "title": "Del mito al logos",
  "md": "# Del mito al logos\n## El paso decisivo\n- Grecia, **s. VI a. C.**: nace la filosofía\n- De explicar por **dioses** a explicar por **razones**\n## Mito (mythos)\n- Relatos de **dioses** con voluntad caprichosa\n- **Antropomórfico y animista**\n- Se transmite por tradición oral\n- **Dogmático**: se acepta sin discutir\n## Logos (razón)\n- Busca **causas naturales** y leyes\n- Se apoya en **argumentos**; tiene autor\n- **Crítico**: se puede discutir y revisar\n## Los primeros filósofos\n- Buscan el **arché** (el principio de todo)\n- **Tales de Mileto**: el agua\n- Lo decisivo: el **cambio de método**"
 },
 "map-fil-logica": {
  "subject": "fil",
  "tema": "Filosofía · Tema 4",
  "title": "Lógica y argumentación",
  "md": "# Lógica y argumentación\n## Qué es la lógica\n### Qué estudia la lógica\n- La **corrección** de los razonamientos\n- La **forma** del pensamiento, no su contenido\n- La fundó **Aristóteles** (teoría del **silogismo**)\n### Proposiciones y argumentos\n- **Proposición**: enunciado verdadero o falso\n- **Argumento**: **premisas** que apoyan una **conclusión**\n- Argumentar es **dar razones**\n### Definir y distinguir\n- **Género próximo** + **diferencia específica**\n- Condición **necesaria** y **suficiente**\n- **Análisis conceptual**: ¿qué es mentir?\n## Razonar bien\n### Modos de razonar\n- **Deducción**: conclusión **necesaria**\n- **Inducción**: de los casos a lo general; solo **probable**\n- **Abducción**: la **mejor explicación** (Peirce)\n- **Analogía**: semejanzas relevantes; riesgo de **falsa analogía**\n### Validez y verdad\n- **Validez**: propiedad de la **forma**\n- **Verdad**: propiedad del **contenido**\n- **Sólido** = válido + premisas verdaderas\n- Una inducción no es válida o inválida, sino **fuerte** o **débil**\n### Lógica formal y simbólica\n- **Frege**: lógica de primer orden\n- **Conectivas** y **tablas de verdad**; **tautología** y **contradicción**\n- **Boole** y **Shannon**: de la lógica a las **puertas lógicas**\n- La **paradoja** del mentiroso\n## Argumentar en la práctica\n### Las falacias\n- Parecen válidas, pero no lo son\n- **Formales** (la forma) e **informales** (el contenido o el lenguaje)\n- *Ad hominem*, *ad populum*, hombre de paja, falsa causa…\n- **Sofisma** (a propósito) y **paralogismo** (sin querer)\n### Analizar y dialogar\n- Indicadores; **premisas implícitas** (**entimema**)\n- **Carga de la prueba** y **principio de caridad**\n- **Contraejemplo** y **reducción al absurdo**\n- Razonar, no **racionalizar**"
 },
 "map-fil-etica": {
  "subject": "fil",
  "tema": "Filosofía · Tema 5",
  "title": "Las preguntas de la ética",
  "md": "# Las preguntas de la ética\n## Qué es la ética\n### Ética y moral\n- **Moral**: normas y valores que rigen en una comunidad\n- **Ética**: reflexión filosófica sobre la moral\n- «¿Cómo debemos vivir?» (**Sócrates**)\n- Niveles: ética **normativa**, **aplicada** y **metaética**\n### La libertad, condición de la moral\n- Sin libertad no hay **responsabilidad**\n- **Autonomía** frente a **heteronomía** (Kant)\n- **Incompatibilismo** y **compatibilismo**\n### ¿Hay verdades morales?\n- **Objetivismo**: hechos morales que valen para todos\n- **Subjetivismo** y **relativismo cultural**\n- **No cognitivismo**: el **emotivismo** (Hume, Ayer)\n- Sin crítica posible no hay **progreso moral**\n## Las grandes teorías\n### Éticas materiales\n- Dicen cuál es el **bien** o el fin: **teleológicas**\n- **Aristóteles**: *eudaimonía*; la virtud como **término medio**\n- **Epicuro**: el placer como *ataraxia*\n- **Utilitarismo** (Bentham, Mill): «la mayor felicidad para el mayor número»\n### La ética formal de Kant\n- **Deontológica**: obrar **por deber**\n- **Imperativo categórico**: una máxima que pueda ser **ley universal**\n- La humanidad, siempre como **fin** y nunca solo como medio\n### Sospecha y casos límite\n- **Nietzsche**: moral de **señores** y de **esclavos**; **transvaloración**\n- El utilitarismo a prueba: el **tranvía** y el trasplante\n- **Singer**: ¿exige demasiado?\n## La ética en la vida\n### El juicio moral\n- **Piaget**: de la moral **heterónoma** a la **autónoma**\n- **Kohlberg**: tres niveles; el **dilema de Heinz**\n- **Gilligan**: la voz del **cuidado**\n### Ética aplicada hoy\n- **Ética del cuidado** (Noddings, Tronto)\n- **Bioética**: autonomía, beneficencia, no maleficencia y justicia\n- Ética **animal** (**especismo**) y ética de la **IA**"
 },
 "map-fil-politica": {
  "subject": "fil",
  "tema": "Filosofía · Tema 6",
  "title": "La vida en sociedad",
  "md": "# La vida en sociedad\n## Sociedad y Estado\n### Un animal político\n- **Aristóteles**: *zoon politikón*\n- Quien vive aislado, «o es una bestia o es un dios»\n- La filosofía política pregunta cómo **deberían** ser las sociedades\n### ¿Por qué existe el Estado?\n- Antiguos: la comunidad política es **natural**\n- Modernos: un artificio, el **contrato social**\n- El **estado de naturaleza**: una hipótesis, no un hecho\n- Críticas: **Hume** (conquista y utilidad) y **Kant** (idea de la razón)\n### Los contractualistas\n- **Hobbes**: guerra de todos contra todos → el **Leviatán**\n- **Locke**: derechos naturales → **Estado liberal** y derecho de resistencia\n- **Rousseau**: **voluntad general** → **soberanía popular**\n## Poder, justicia y gobierno\n### Poder y legitimidad\n- **Poder**: hacer que otros obedezcan\n- **Legitimidad**: el derecho a mandar\n- **Weber**: tradición, carisma y **legalidad racional**\n### La justicia\n- **Distributiva** y **correctiva** (Aristóteles)\n- **Rawls**: **velo de ignorancia** y **principio de diferencia**\n- **Nozick**: la titularidad y el **Estado mínimo**\n- **Comunitarismo** (Sandel): los bienes que compartimos\n### Formas de gobierno\n- Uno, pocos, muchos: **monarquía**, **aristocracia**, **politeia**\n- Degeneradas, en interés propio: **tiranía**, **oligarquía** y, para Aristóteles, **democracia**\n- Democracia moderna: **liberal**, **deliberativa**, **participativa**\n- Amenazas: **tiranía de la mayoría**, **populismo**, erosión desde dentro\n## Derechos y futuro\n### Derechos y libertad\n- **Derechos humanos** (1948): tres **generaciones**\n- **Estado de derecho** frente a **totalitarismo** (Arendt)\n- **Berlin**: libertad **negativa** y libertad **positiva**\n### Imaginar y ampliar el pacto\n- **Utopías** (Platón, Moro) y **distopías** (Huxley, Orwell)\n- **Feminismo**: patriarcado, **sexo y género**, interseccionalidad\n- «No se nace mujer: se llega a serlo» (**Beauvoir**)"
 },
 "map-fil-estetica": {
  "subject": "fil",
  "tema": "Filosofía · Tema 7",
  "title": "¿Qué es el arte?",
  "md": "# ¿Qué es el arte?\n## Belleza y gusto\n### La estética\n- Reflexiona sobre la **belleza**, el **arte** y la **experiencia estética**\n- Del griego *aísthesis*: sensación (**Baumgarten**)\n- Contemplar algo **por sí mismo**, sin buscar su uso\n### ¿Dónde está la belleza?\n- **Objetiva** (clásica): proporción, armonía, orden y medida\n- Pitagóricos, **Policleto** (*Canon*), Agustín, Tomás\n- **Subjetiva** (moderna): el placer de quien mira\n- Otras categorías: **lo sublime**, lo feo, lo trágico, lo cómico\n### El juicio del gusto\n- **Hume**: el **crítico competente**\n- **Kant**: **desinteresado** y **universal sin concepto**\n- **Finalidad sin fin**; belleza **libre** y **adherente**\n## Qué es el arte\n### Teorías del arte\n- **Imitación** (*mímesis*): representar la realidad\n- **Expresión** (Romanticismo): la emoción del autor\n- **Forma** (formalismo): composición, color, ritmo\n- **Institucional** (Danto, Dickie): lo que reconoce el mundo del arte\n### Arte y verdad\n- **Platón**: copia de una copia; el arte **engaña**\n- **Aristóteles**: *mímesis* y **catarsis**\n- **Hegel**: el «**fin del arte**»\n- **Heidegger** y **Gadamer**: la obra abre un mundo\n## Arte y sociedad\n### Arte, emoción y moral\n- El arte **educa** los sentimientos\n- **Schiller**: el **juego** y la educación estética\n- **Moralismo** frente a **autonomismo** («arte por el arte»)\n### Arte y política\n- **Arte comprometido** frente a **arte por el arte**\n- **Benjamin**: el fascismo **estetiza la política**\n- **Adorno**: la **industria cultural**\n### La imagen hoy\n- **Duchamp** y el **ready-made**\n- **Benjamin**: reproductibilidad técnica y pérdida del **aura**\n- **Debord** (espectáculo) y **Baudrillard** (**simulacro**)\n- **Alfabetización visual**: mirar críticamente"
 },
 "map-fil-metafisica": {
  "subject": "fil",
  "tema": "Filosofía · M",
  "title": "La realidad: ¿qué hay?",
  "md": "# La realidad: ¿qué hay?\n## La metafísica\n- Pregunta **qué existe** y cómo es en último término\n- *Ta meta ta physika*; la «**filosofía primera**» de Aristóteles\n- **Ontología**: qué tipos de cosas existen\n- Críticas: **Kant** y el **Círculo de Viena**\n## Apariencia y realidad\n- **Parménides**: el ser es uno e inmutable; el cambio, apariencia\n- **Platón**: mundo **sensible** y mundo de las **Ideas**\n- **Bostrom**: el argumento de la **simulación**\n## ¿De qué está hecho todo?\n- **Monismo** (Spinoza), **dualismo** (Descartes), **pluralismo** (Empédocles, Leibniz)\n- **Materialismo**: todo es materia (Demócrito, Hobbes, el fisicalismo)\n- **Idealismo**: «ser es ser percibido» (**Berkeley**)\n## Sustancia, esencia y existencia\n- **Aristóteles**: la **sustancia** y sus **accidentes**\n- **Hilemorfismo**: **materia** + **forma**\n- **Acto** y **potencia**: así se explica el cambio\n- **Sartre**: «la existencia precede a la esencia»"
 },
 "map-fil-metafisica-2": {
  "subject": "fil",
  "tema": "Filosofía · M",
  "title": "La realidad: mente, tiempo, libertad y Dios",
  "md": "# La realidad: mente, tiempo, libertad y Dios\n## Mente y tiempo\n### Mente, cuerpo e IA\n- **Dualismo**: ¿cómo interactúan? (Isabel de Bohemia)\n- **Teoría de la identidad**: estados del cerebro\n- **Funcionalismo** (Putnam): la mente se define por su función\n- El **test de Turing** frente a la **habitación china** (Searle)\n- El **problema difícil** de la conciencia (Chalmers)\n### El tiempo y el cambio\n- **Heráclito**: todo cambia (el río)\n- **Zenón**: Aquiles y la tortuga\n- El **barco de Teseo** (Plutarco): ¿sigue siendo el mismo?\n- **Newton** (tiempo absoluto) frente a **Leibniz** (relativo); **Einstein**\n- **Presentismo** y **eternalismo**\n## Libertad y Dios\n### ¿Somos libres?\n- **Determinismo** (el demonio de Laplace) e **indeterminismo**\n- **Determinismo duro**: la libertad es una ilusión\n- **Libertarismo**: podríamos haber obrado de otro modo\n- **Compatibilismo**: ser libre es actuar sin **coacción**\n### ¿Existe Dios?\n- Argumento **ontológico** (Anselmo)\n- Argumento **cosmológico** (las cinco vías) y del **diseño** (Paley)\n- En contra: el **problema del mal**; respuesta: la **teodicea**\n- Caso aparte: la **apuesta de Pascal**\n- **Teísmo**, **ateísmo**, **agnosticismo** y **fideísmo**"
 },
 "map-fil-cuerpo-mente": {
  "subject": "fil",
  "tema": "Filosofía · Tema 2",
  "title": "El cuerpo y la mente",
  "md": "# El cuerpo y la mente\n## El problema mente-cuerpo\n- ¿Somos **una** cosa o **dos**?\n## Dualismo (dos realidades)\n- Cuerpo **material** + alma **inmaterial** (lo esencial)\n- **Platón** — alma inmortal, cuerpo «cárcel»; carro alado; alma en 3 partes (racional, irascible, concupiscible)\n- **Descartes** — res cogitans (mente) vs res extensa (cuerpo-máquina)\n## Monismo materialista (una realidad)\n- Solo hay **cuerpo**; la mente es su **actividad** (el cerebro)\n- **Demócrito**, **Hobbes**, **La Mettrie** (el hombre máquina); hoy, **Dennett** y los **Churchland**\n## Los problemas\n- Dualismo: ¿cómo se comunican mente y cuerpo?\n- Monismo: ¿somos **libres** o solo química?"
 }
};
